fail_fast: false
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: remove-tabs
        exclude: "vendor-prefixes\\.txt$"
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args:
          - -i
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        # Workaround for https://github.com/pre-commit/mirrors-prettier/issues/29
        additional_dependencies:
          - prettier@2.8.7
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
        exclude: "\\.mustache$"
  - repo: https://github.com/Quard/license-header-checker
    rev: v0.1
    hooks:
      - id: license-header-checker
        files: \.(c|h|dtsi|dts|overlay|keymap)$
        exclude: ^((app/boards/)|(app/tests/))
        args:
          - --comment-style
          - "/*| *| */"
          - --license
          - "\\nCopyright \\(c\\) \\d{4}(-\\d{4})? The ZMK Contributors\\n\\nSPDX-License-Identifier: MIT\\n"
      - id: license-header-checker
        files: (\.yaml)|(CMakeLists.txt)|(Kconfig)$
        exclude: ^((app/boards/)|(app/tests/)|(\.pre-commit-config.yaml))
        args:
          - --comment-style
          - "#"
          - --license
          - "Copyright \\(c\\) \\d{4}(-\\d{4})? The ZMK Contributors\\nSPDX-License-Identifier: MIT"
